#!/bin/bash

#check if file is provided
if [-z "$1" ]; then
    echo "Usage: $0 <clrtoscan_file>"
    exit 1
fi

#read file line by line while filtering comments and headers
while read -r file host port auth; do
        ase "$file" in
        CLRTOSCAN*|START-LIST*|END-LIST*|\#*|"")
            continue
            ;;
    esac

#grab and display status of client
        echo "Fetching $file from $host:$port..."
    ./cgrab "$file" "$host" "$port" "$auth"

done < "$1"
